name: ROS 2 CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    name: Build and test the project
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and test
        uses: threeal/ros2-ci@v0.1
